version: '3'
services:
    reverseproxy:
        build:
            context: .
            dockerfile: Dockerfile-Reverseproxy
        ports:
            - 8000:8000
        links:
            - airports
            - countries
        container_name: reverseproxy
        restart: always
 
    airports:
        build:
            context: .
            dockerfile: Dockerfile-airports
        ports:
            - "8080"
        container_name: airports
        restart: always
 
    countries:
        build:
            context: .
            dockerfile: Dockerfile-countries
        ports:
            - "8080"
        container_name: countries
        restart: always
